parent(paul,lily).
parent(paul,petunia).
parent(helen,lily).
parent(helen,petunia).
parent(albert,james).
parent(ruth,james).
parent(lily,harry).
parent(james,harry).
parent(vernon,dudley).
parent(petunia,dudley).
male(paul).
male(albert).
male(james).
male(vernon).
female(lily).
female(helen).
female(petunia).
female(ruth).